version: '3.9'

services:
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80
    restart: always
    depends_on:
      - django_app
  django_app:
    image: django_app
    build: 
      context: ./app
    container_name: "django_cont"
    restart: always
    env_file:
      - .env
    ports:
      - 8001:8001
    command: gunicorn intranet.wsgi --bind 0.0.0.0:8001
    depends_on:
      - db
  db:
    image: mariadb
    container_name: "db_cont"
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}