# Generated by Django 5.0.4 on 2025-04-02 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_profile_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('fecha_contacto', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('comercial', models.ForeignKey(help_text='El rol debe ser "comercial"', limit_choices_to={'rol': 'comercial'}, on_delete=django.db.models.deletion.CASCADE, to='usuarios.profile')),
            ],
        ),
    ]
