# Generated by Django 5.0.4 on 2025-04-11 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_espesor_proveedor_ubicacion_remove_cliente_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Montador',
            fields=[
                ('id_montador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('zona_servicio', models.CharField(max_length=255)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
        migrations.CreateModel(
            name='ProductoEspecifico',
            fields=[
                ('id_prod_espe', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_acabado', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_especifico', to='productos.cliente')),
                ('montador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_especifico', to='productos.montador')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_especifico', to='productos.producto')),
                ('ubicacion', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto_especifico', to='productos.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProducto',
            fields=[
                ('id_estado_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('fecha_estado', models.DateTimeField(blank=True, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('producto_especifico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='productos.productoespecifico')),
            ],
        ),
    ]
