# Generated by Django 5.0.4 on 2025-04-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_producto_num_banios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productoespecifico',
            old_name='fecha_acabado',
            new_name='fecha_acabado_montaje',
        ),
        migrations.RenameField(
            model_name='productoespecifico',
            old_name='fecha_inicio',
            new_name='fecha_inicio_montaje',
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='productos_t_nombre_bcb11f_idx')],
            },
        ),
    ]
