# Generated by Django 5.0.4 on 2025-04-11 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_remove_productoespecifico_ubicacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoespecifico',
            name='materiales',
            field=models.ManyToManyField(blank=True, null=True, related_name='productos_especificos', to='productos.material'),
        ),
        migrations.AddField(
            model_name='productoespecifico',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
