# Generated by Django 5.0.4 on 2025-04-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_remove_productoespecifico_materiales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocliente',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='estadocliente',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='estadoproducto',
            name='fecha_estado',
        ),
        migrations.RemoveField(
            model_name='estadoproducto',
            name='producto_especifico',
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.estadocliente'),
        ),
        migrations.AddField(
            model_name='productoespecifico',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.estadoproducto'),
        ),
    ]
