# Generated by Django 5.0.4 on 2025-04-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0011_remove_estadocliente_fecha_estado_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
    ]
