# Generated by Django 5.0.4 on 2025-05-07 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0012_alter_cliente_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
