# Generated by Django 5.0.4 on 2025-05-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='num_cocina',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
