# Generated by Django 5.0.4 on 2025-05-20 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0016_remove_productoespecifico_envio_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoespecifico',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.estadoproducto'),
        ),
    ]
