# Generated by Django 5.0.4 on 2025-05-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0018_productoespecifico_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoespecifico',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='producto_especifico', to='productos.producto'),
        ),
    ]
