# Generated by Django 5.0.4 on 2025-04-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d'),
        ),
    ]
