# Generated by Django 5.0.4 on 2025-04-03 15:18

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_profile_rol_rol_profile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imagen',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Juan\\Desktop\\working\\PROYECTO_INTRANET\\proyecto-intranet\\static'), upload_to='users/%Y/%m/%d'),
        ),
    ]
