# Generated by Django 5.0.4 on 2025-04-10 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('usuarios', '0006_alter_profile_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espesor',
            fields=[
                ('id_espesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('revestimiento', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=255)),
                ('nota', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='estado',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nota',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='via_entrada',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comercial',
            field=models.ForeignKey(help_text='El rol debe ser "comercial"', limit_choices_to={'rol': 'comercial'}, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.profile'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_contacto',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_habitaciones', models.IntegerField()),
                ('num_banios', models.IntegerField()),
                ('num_plantas', models.IntegerField()),
                ('pared_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('suelo_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tejado_m2', models.DecimalField(decimal_places=2, max_digits=6)),
                ('espesores', models.ManyToManyField(blank=True, related_name='espesores', to='productos.espesor')),
                ('ubicacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='productos.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('fecha_estado', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='productos.cliente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='productos.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id_material', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('slug', models.SlugField(unique=True)),
                ('proveedores', models.ManyToManyField(blank=True, related_name='materiales', to='productos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='EnvioMaterial',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('listo_envio', 'Listo para envío'), ('fabricando', 'Fabricando'), ('pendiente_planos', 'Pendiente de confirmar los planos')], default='pendiente_planos', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('nota', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='productos.material')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='productos.proveedor')),
            ],
        ),
    ]
