# Generated by Django 5.0.4 on 2025-04-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_rename_fecha_acabado_productoespecifico_fecha_acabado_montaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_productos',
            field=models.ManyToManyField(related_name='tipos', to='productos.tipoproducto'),
        ),
    ]
