# Generated by Django 5.0.4 on 2025-04-11 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_tipo_productos'),
        ('usuarios', '0006_alter_profile_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoespecifico',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='producto_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ubicaciones', to='productos.productoespecifico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='comercial',
            field=models.ForeignKey(help_text='El rol debe ser "comercial"', limit_choices_to={'roles__slug': 'comercial'}, on_delete=django.db.models.deletion.RESTRICT, to='usuarios.profile'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
