# Generated by Django 5.0.4 on 2025-04-23 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_productoespecifico_materiales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoespecifico',
            name='materiales',
        ),
        migrations.RemoveField(
            model_name='productoespecifico',
            name='producto',
        ),
        migrations.AddField(
            model_name='enviomaterial',
            name='producto_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='productos.productoespecifico'),
        ),
        migrations.AddField(
            model_name='productoespecifico',
            name='envio_material',
            field=models.ManyToManyField(blank=True, related_name='productos_especificos', to='productos.enviomaterial'),
        ),
        migrations.AddField(
            model_name='productoespecifico',
            name='fecha_acabado_montaje_estimado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enviomaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_material', to='productos.material'),
        ),
        migrations.AlterField(
            model_name='enviomaterial',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_material', to='productos.proveedor'),
        ),
        migrations.AlterField(
            model_name='productoespecifico',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='EnvioProducto',
            fields=[
                ('id_envio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_llegada_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('listo_envio', 'Listo para envío'), ('fabricando', 'Fabricando'), ('pendiente_planos', 'Pendiente de confirmar los planos')], default='pendiente_planos', max_length=50)),
                ('cantidad', models.IntegerField(default=1)),
                ('nota', models.TextField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_producto', to='productos.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_producto', to='productos.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='productoespecifico',
            name='envio_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_especificos', to='productos.envioproducto'),
        ),
    ]
