# Generated by Django 5.0.4 on 2025-04-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_remove_estadocliente_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estadocliente',
            name='fecha_estado',
        ),
        migrations.RemoveField(
            model_name='estadoproducto',
            name='nota',
        ),
    ]
