# Generated by Django 5.0.4 on 2025-05-15 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0014_producto_num_cocina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='espesores',
            field=models.ManyToManyField(blank=True, related_name='productos', to='productos.espesor'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_productos',
            field=models.ManyToManyField(related_name='productos', to='productos.tipoproducto'),
        ),
    ]
