# Generated by Django 5.0.4 on 2025-05-20 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0015_alter_producto_espesores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoespecifico',
            name='envio_material',
        ),
        migrations.RemoveField(
            model_name='productoespecifico',
            name='envio_producto',
        ),
        migrations.RemoveField(
            model_name='productoespecifico',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='productoespecifico',
            name='nota',
        ),
        migrations.AddField(
            model_name='envioproducto',
            name='producto_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_producto', to='productos.productoespecifico'),
        ),
        migrations.AlterField(
            model_name='enviomaterial',
            name='producto_especifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='envios_material', to='productos.productoespecifico'),
        ),
    ]
