# Generated by Django 5.0.4 on 2025-05-21 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0017_productoespecifico_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoespecifico',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='producto_especifico', to='productos.producto'),
        ),
    ]
