# Generated by Django 5.0.4 on 2025-07-29 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0020_alter_ubicacion_latitud_alter_ubicacion_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='espesores',
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.CreateModel(
            name='ProductoEspesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('espesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_producto', to='productos.espesor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_espesor', to='productos.producto')),
            ],
            options={
                'unique_together': {('producto', 'espesor')},
            },
        ),
    ]
