# Generated by Django 5.0.4 on 2025-07-29 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0021_remove_producto_espesores_alter_ubicacion_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
    ]
